### PR TITLE
Less bh param

### PR DESCRIPTION
**Pull request by rainwoodman**

### CODE REVIEW

**Comment by sbird** [comment]
The only one I am concerned about is WindModel, as it implicitly includes "nowind": Everything else has a "XXXOn" parameter which is required.

**Comment by rainwoodman** [comment]
The twist is that wind is part of SFR. nowind is a special type of wind feedback. We can also think of wind as a separate module that depends on SFR -- but it introduces a module dependency and I think it is not easy to handle..

**Comment by rainwoodman** [comment]
I think we shall make the WindModel default sh03 -- which is the canonical model.

**Comment by sbird** [comment]
Ok, fair enough.

I would make the default what is in BlueTides and Illustris (which I think is what you have?). sh03 is canonical but a bad fit to reality.

**Comment by rainwoodman** [comment]
I read the code again and agree with adding WindOn. The default shall be something like ojft10 then, and the criteria shall have H2..

**Comment by sbird** [comment]
Sounds good to me.

**Comment by sbird** [comment]
I am happy for this to be merged.

**Comment by rainwoodman** [comment]
Sure. I'm waiting for travis to turn green.

**Pull request merged**
