### PR TITLE
Extratests

### PR DESCRIPTION
**Pull request by sbird**
This pull request adds some unit tests for the cosmology module and the timefac module. It then makes sure they pass.

This means:
- Porting the better growth function solutions from N-GenIC (only affects GenIC with radiation on)
- Slightly increasing the size of the lookup table in timefac.c

There are also some (largely unrelated) cleanups to the prediction functions, and I remove TypeOfOpeningCriterion because we never used it.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Looked good to my eyes. 

What's the purpose for adding Ti_current to Prec?

I am hoping in the near future we can remove these threadprivate caches. As we drift to Ti_current the we can compute the factors for prediction of each time bin (since we know the current time of the timebin). Then the Pred functions can directly use the time bin do make the prediction. Which means they always pred to Ti_current, thus it shall not be a parameter to Pred functions.

**Comment by sbird** [comment]
Exactly! This is why I am removing the Ti_Current argument (I think you are viewing the diff backwards).

**Comment by sbird** [comment]
See some partial work in that direction in the recently pushed out_timestep3

**Comment by rainwoodman** [comment]
Oops. I did.

**Comment by sbird** [comment]
Note by the way that this branch will change the output of N-GenIC (for the better) and may slightly change the particle output (because the drift table is marginally more accurate).

**Comment by rainwoodman** [comment]
And D is correct. Merge this and rebase out_timestep3?

**Comment by sbird** [comment]
Ok!

**Pull request merged**
