### PR TITLE
Checkforce

### PR DESCRIPTION
**Pull request by rainwoodman**
This branch adds some infrastructure for testing (RestartFlag = 99), as well as adds a new pair wise short range force module. It is hell a lot slower than the tree! (x2?), but the results seem to be consistent.

There is a vast clean up regarding TimeBegin. It is no longer read from the parameter files. Also IonizeParam is moved into set_global_time.

RestartFlag and RestartSnapNum are now local variables.

### CODE REVIEW

**Comment by sbird** [comment]
Ok, go for it. Neutrino merge is not yet. We always reserve the ability to advertise at some later date.

**Comment by sbird** [comment]
hm - then it is weird a bit that the force error is so large. Is this running on MPI?

**Comment by rainwoodman** [comment]
I had some tests regarding MPI in the notebook. 1 rank and 4 ranks gave identical forces.

**Comment by sbird** [comment]
I wonder if the large errors are just particles with small absolute force (and so it doesn't matter much)?

**Comment by rainwoodman** [comment]
Yes. They are. The dots are the 400 most different particles.

[image: Inline image 1]

**Comment by sbird** [comment]
I can't see that image but that sounds like not a problem then.

**Comment by rainwoodman** [comment]
image

**Comment by rainwoodman** [comment]
I'll attach the image for the record. (didn't know now I can copy and paste from a notebook to github comments.

**Pull request merged**
