### PR TITLE
Remove requirement particles sorted by type before IO

### PR DESCRIPTION
**Pull request by rainwoodman**
This remove the requirement that particles must be sorted by type before IO.

### CODE REVIEW

**Comment by sbird** [comment]
Ok, I'm curious - this seems fine, but why did you want to do it? It was only implemented a few weeks ago, at your suggestion.

**Comment by rainwoodman** [comment]
i realized we cannot assume the particles are sorted by type due to GC.

**Comment by rainwoodman** [comment]
I noticed this because when i ran lya on static tree it always crashed
without this fix.

On Sep 9, 2017 3:38 PM, "Feng Yu" <rainwoodman@gmail.com> wrote:

i realized we cannot assume the particles are sorted by type due to GC.

**Comment by sbird** [comment]
Makes sense. I guess I hadn't tested far enough to get star formation just before a snapshot.

**Pull request merged**
