### PR TITLE
Nbkittest

### PR DESCRIPTION
**Pull request by rainwoodman**

### CODE REVIEW

**Comment by sbird** [comment]
Nice! Why not check the power of the snapshots output by MP-Gadget as well? That's a quite powerful consistency check.

**Comment by rainwoodman** [comment]
I wonder if there is a way we can add some assertion of the stability of the result. Probably worth working it out using #118 as a test of the test?

**Comment by sbird** [comment]
What do you mean by "stability of the result"? Do you mean that the output should remain the same? I guess we would need then to add some "known-good" data somewhere (or we could just check against CAMB with sigma_8 = 0.05, so everything is linear).

**Comment by rainwoodman** [comment]
I added assertions on the growth -- that was OK from (a=0.1 to a=0.2ish), so it is pretty much the same as setting sigma8 = 0.05. (but with very few time steps)

The problem occurs asserting the power of IC/PART_000.

I find with nbodykit 0.2.6 the measured IC power disagrees with the truth IC at ~7% (systematically lower), but with nbodykit 0.2.7 the difference is within 5%. then there was some slight tweaking of handling of cosmology parameters in nbodykit between the two versions.

The 5% error is still a bit strange. The cosmology is slightly different -- nbkit uses class which contains radiation in the bg, but the travis test currently doesn't. (maybe we shall at it?).

ZA also introduces a difference from the linear spectrum. (you mentioned the mesh res is low enough for this to be an effect)

It may also is due to the sigma8 normalization, which may have shifted the entire spectrum before using it.

**Comment by sbird** [comment]
I will take a look next week. It may indeed be due to the scaling

**Comment by rainwoodman** [comment]
Perhaps we can merge this one first since it is already green?

**Comment by sbird** [comment]
Do it!

**Comment by rainwoodman** [comment]
Merged. Let's rebase the dangling PRs and hope they workout fine..

**Pull request merged**
